Hist Gradient Boosting:
  learning_rate: [0.1, 0.01, 0.05, 0.001]
  max_iter: [100, 200, 300]
  max_depth: [3, 5, 10]

Linear Regression:
  fit_intercept: [True, False]

XGBRegressor:
  learning_rate: [0.1, 0.01, 0.05, 0.001]
  n_estimators: [8, 16, 32, 64, 128, 256]
  max_depth: [3, 5, 7, 10]
  device: ['cuda']
  tree_method: ['hist']

CatBoost Regressor:
  depth: [6, 8, 10]
  learning_rate: [0.01, 0.05, 0.1]
  iterations: [30, 50, 100]
  task_type: ['GPU']
  devices: ['0']
